services:
  - type: web
    name: SchoolConnect
    runtime: node
    rootDir: back-end
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: PORT
        value: 3002
      - key: NODE_ENV
        value: production
      - key: SECRET_KEY
        sync: false
      - key: EXPIRATION_TIME
        value: 1h
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_SENHA
        sync: false
    disk:
      name: schoolconnect-db
      mountPath: /opt/render/project/src/back-end
      sizeGB: 1